/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Propietario;

/**
 * Ventana principal para gestionar los propietarios registrados en el
 * sistema. Muestra la lista de propietarios en una tabla, permite
 * buscarlos en tiempo real, y da acceso a insertar, editar o eliminar
 * registros.
 * 
 * @author graci
 */
public class DlgMainPropietarios extends javax.swing.JDialog {

    /**
     * Lista de propietarios mostrada y modificada en esta ventana.
     */
    private ArrayList<Propietario> listaProp;
    /**
     * Modelo de la tabla de propietarios.
     */
    private DefaultTableModel model;
    
    public DlgMainPropietarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * Crea la ventana principal de propietarios, cargando los datos
     * existentes y activando la búsqueda en tiempo real sobre la tabla.
     *
     * @param parent ventana padre
     * @param modal si el diálogo es modal
     * @param listaProp lista de propietarios a mostrar y modificar
     */
    public DlgMainPropietarios(java.awt.Frame parent, boolean modal, ArrayList<Propietario> listaProp) {
        super(parent, modal);
        initComponents();
        this.listaProp = listaProp;
        mostrarDatos();
        txtBuscar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { filtrar(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { filtrar(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { filtrar(); }});
    }
    
    /**
     * Obtiene la lista de propietarios, ya actualizada tras cualquier cambio.
     *
     * @return la lista de propietarios
     */
    public ArrayList<Propietario> getListaProp() {
    return listaProp;
    }
    
    /**
     * Carga la tabla con todos los propietarios de la lista.
     */
    public void mostrarDatos(){
        String[] columnas = {"Cédula", "Nombre", "Género", "Teléfono", "Email"};
        model = new DefaultTableModel(null, columnas);
        tblPropietarios.setModel(model);
        
        for (Propietario p : listaProp){
            Object[] fila = {
                p.getCedPropiet(),
                p.getNomPropiet(),
                p.getGenero(),
                p.getDireccion(),
                p.getTelefono(),
                p.getEmail()
            };
            model.addRow(fila);
        }
    }
    
    /**
     * Filtra la tabla según el texto escrito en txtBuscar, comparando
     * contra la cédula y el nombre del propietario.
     */
    private void filtrar() {
    String texto = txtBuscar.getText().trim().toLowerCase();
    
    model = new DefaultTableModel(null, new String[]{"Cédula", "Nombre", "Género", "Dirección", "Teléfono", "Email"});
    tblPropietarios.setModel(model);
    
    for (Propietario p : listaProp) {
        boolean coincideCedula = String.valueOf(p.getCedPropiet()).contains(texto);
        boolean coincideNombre = p.getNomPropiet().toLowerCase().contains(texto);
        
        if (texto.isEmpty() || coincideCedula || coincideNombre) {
            Object[] fila = {
                p.getCedPropiet(),
                p.getNomPropiet(),
                p.getGenero(),
                p.getDireccion(),
                p.getTelefono(),
                p.getEmail()
            };
            model.addRow(fila);
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPropietarios = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Propietarios");

        tblPropietarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPropietarios);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar:");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsertar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCerrar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre DlgNewPropietario en modo Agregar y refresca la tabla al cerrar.
     *
     * @param evt evento de clic sobre el botón Insertar
     */
    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        DlgNewPropietario dlg = new DlgNewPropietario(null, true, listaProp, 1);
        dlg.setVisible(true);
        mostrarDatos(); //refresca la tabla con el nuevo propietario
    }//GEN-LAST:event_btnInsertarActionPerformed

    /**
     * Abre DlgNewPropietario en modo Editar con el propietario seleccionado
     * en la tabla.
     *
     * @param evt evento de clic sobre el botón Editar
     */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tblPropietarios.getSelectedRow();
        if (fila == -1){
            JOptionPane.showMessageDialog(this, "Seleccione un propietario de la tabla");
            return;
        }
        Propietario p = listaProp.get(fila);
        DlgNewPropietario dlg = new DlgNewPropietario(null, true, listaProp, 2, p, fila);
        dlg.setVisible(true);
        mostrarDatos();
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * Elimina el propietario seleccionado en la tabla, previa confirmación
     * del usuario.
     *
     * @param evt evento de clic sobre el botón Eliminar
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblPropietarios.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un propietario de la tabla");
        return;
    }
    int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Está segura de eliminar este propietario?",
            "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
    if (confirmacion == JOptionPane.YES_OPTION) {
        listaProp.remove(fila);
        mostrarDatos();
        JOptionPane.showMessageDialog(this, "Propietario eliminado");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgMainPropietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgMainPropietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgMainPropietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgMainPropietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgMainPropietarios dialog = new DlgMainPropietarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPropietarios;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
