/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Propietario;
import modelo.Vivienda;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class DlgMainViviendas extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgMainViviendas.class.getName());

    /**
     * Lista de viviendas mostrada y modificada en esta ventana.
     */
    private ArrayList<Vivienda> listaVivienda;

    /**
     * Lista de propietarios existentes, necesaria para abrir DlgNewVivienda.
     */
    private ArrayList<Propietario> listaProp;

    /**
     * Modelo de la tabla de viviendas.
     */
    private DefaultTableModel model;

    public DlgMainViviendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Crea la ventana principal de viviendas, cargando los datos EXISTENTES y activa la búsqueda en tiempo real.
     *
     * @param parent ventana padre
     * @param modal si el diálogo es modal
     * @param listaVivienda lista de viviendas a mostrar y modificar
     * @param listaProp lista de propietarios EXISTENTES
     */
    public DlgMainViviendas(java.awt.Frame parent, boolean modal, ArrayList<Vivienda> listaVivienda, ArrayList<Propietario> listaProp) {
        super(parent, modal);
        initComponents();
        this.listaVivienda = listaVivienda;
        this.listaProp = listaProp;
        mostrarDatos();
        txtBuscar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filtrar();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filtrar();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filtrar();
            }
        });
    }

    /**
     * Obtiene la lista de viviendas, ya actualizada tras cualquier cambio.
     *
     * @return la listaVivienda
     */
    public ArrayList<Vivienda> getListaVivienda() {
        return listaVivienda;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViviendas = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtBuscar.addActionListener(this::txtBuscarActionPerformed);

        lblBuscar.setText("Buscar:");

        tblViviendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblViviendas);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Carga la tabla con todas las viviendas de la lista.
     */
    public void mostrarDatos() {
        String[] columnas = {"ID", "Descripción", "Dirección", "Propietario", "Precio Base", "Estado"};
        model = new DefaultTableModel(null, columnas);
        tblViviendas.setModel(model);

        for (Vivienda vivienda : listaVivienda) {
            Object[] fila = {
                vivienda.getIdVivienda(),
                vivienda.getDescripcion(),
                vivienda.getDireccion(),
                vivienda.getPropietario(),
                vivienda.getPrecioBase(),
                vivienda.getEstado()
            };
            model.addRow(fila);
        }
    }

    /**
     * Filtra la tabla según el texto escrito en txtBuscar, comparando contra el id de la vivienda y su descripción.
     */
    private void filtrar() {
        String texto = txtBuscar.getText().trim().toLowerCase();

        model = new DefaultTableModel(null, new String[]{"ID", "Descripción", "Dirección", "Propietario", "Precio Base", "Estado"});
        tblViviendas.setModel(model);

        for (Vivienda vivienda : listaVivienda) {
            boolean coincideId = String.valueOf(vivienda.getIdVivienda()).contains(texto);
            boolean coincideDescripcion = vivienda.getDescripcion().toLowerCase().contains(texto);

            if (texto.isEmpty() || coincideId || coincideDescripcion) {
                Object[] fila = {
                    vivienda.getIdVivienda(),
                    vivienda.getDescripcion(),
                    vivienda.getDireccion(),
                    vivienda.getPropietario(),
                    vivienda.getPrecioBase(),
                    vivienda.getEstado()
                };
                model.addRow(fila);
            }
        }
    }

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    /**
     * Abre DlgNewVivienda en modo Agregar y refresca la tabla al cerrar.
     *
     * @param evt evento de clic sobre el botón Insertar
     */
    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        DlgNewVivienda dlg = new DlgNewVivienda(null, true, listaVivienda, listaProp, 1);
        dlg.setVisible(true);
        mostrarDatos();
    }//GEN-LAST:event_btnInsertarActionPerformed

    /**
     * Abre DlgNewVivienda en modo Editar con la vivienda seleccionada en la tabla.
     *
     * @param evt evento de clic sobre el botón Editar
     */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tblViviendas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una vivienda de la tabla");
            return;
        }
        Vivienda viviendaSeleccionada = listaVivienda.get(fila);
        DlgNewVivienda dlg = new DlgNewVivienda(null, true, listaVivienda, listaProp, 2, viviendaSeleccionada, fila);
        dlg.setVisible(true);
        mostrarDatos();
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * Elimina la vivienda seleccionada en la tabla, también lanza mensaje de confirmación antes.
     *
     * @param evt evento de clic sobre el botón Eliminar
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblViviendas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una vivienda de la tabla");
            return;
        }
        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar esta vivienda?",
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            listaVivienda.remove(fila);
            mostrarDatos();
            JOptionPane.showMessageDialog(this, "Vivienda eliminada");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgMainViviendas dialog = new DlgMainViviendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JTable tblViviendas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
