/**
 * Pantalla que permite generar automáticamente las mensualidades de los
 * alquileres vigentes para un mes/año, y consultar/filtrar las mensualidades
 * ya generadas.
 *
 * @author Anais
 */
package vista;
import java.util.ArrayList;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Alquileres;
import modelo.Inquilino;
import modelo.Mensualidades;

 /**
 * Crea la ventana de gestión de mensualidades.
 *
 * @param parent ventana padre
 * @param modal si la ventana bloquea la interacción con el resto del sistema
 * @param listaAlquileres ArrayList con todos los alquileres registrados
 * @param listaInquilinos ArrayList con todos los inquilinos registrados
 * @param listaMensualidades ArrayList con todas las mensualidades registradas
 */
public class DlgMensualidades extends javax.swing.JDialog {
    
    private ArrayList<Alquileres> listaAlquileres;
    private ArrayList<Inquilino> listaInquilinos;
    private ArrayList<Mensualidades> listaMensualidades;
    private DefaultTableModel model;
    
    /**
     * Creates new form DlgGenerarMensualidades
     */
   public DlgMensualidades(java.awt.Frame parent, boolean modal, ArrayList<Alquileres> listaAlquileres,
        ArrayList<Inquilino> listaInquilinos, ArrayList<Mensualidades> listaMensualidades) {
    super(parent, modal);
    initComponents();
    this.listaAlquileres = listaAlquileres;
    this.listaInquilinos = listaInquilinos;
    this.listaMensualidades = listaMensualidades;
    txtFechaActual.setText(LocalDate.now().toString());
    mostrarDatos();

    txtFiltro.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        public void insertUpdate(javax.swing.event.DocumentEvent e) { filtrar(); }
        public void removeUpdate(javax.swing.event.DocumentEvent e) { filtrar(); }
        public void changedUpdate(javax.swing.event.DocumentEvent e) { filtrar(); }
    });
}
    /**
    * Carga en la tabla todos los registros de mensualidades existentes.
    */
    public void mostrarDatos() {
    String[] columnas = {"Consecutivo", "Núm Alquiler", "Fecha Creación", "Inquilino", "Mes en Cobro", "Año", "Descuento", "Monto a pagar", "Estado"};
    model = new DefaultTableModel(null, columnas);
    tblMensualidades.setModel(model);

    for (Mensualidades m : listaMensualidades) {
        Object[] fila = {
            m.getConsecutivo(),
            m.getNumAlquiler(),
            m.getFechCreacion(),
            m.getNomInquilino(),
            m.getMesCobro(),
            m.getAnioActual(),
            m.getDescuento() + "%",
            m.getMontoMes(),
            m.getEstado()
            };
            model.addRow(fila);
        }
    }
    
    /**
    * Filtra los registros de la tabla según los criterios marcados
    * (Inquilino, Mes, Año) y el texto ingresado en el campo de búsqueda.
    */
    private void filtrar() {
    String texto = txtFiltro.getText().trim().toLowerCase();

    String[] columnas = {"Consecutivo", "Núm Alquiler", "Fecha Creación", "Inquilino", "Mes en Cobro", "Año", "Descuento", "Monto a pagar", "Estado"};
    model = new DefaultTableModel(null, columnas);
    tblMensualidades.setModel(model);

    for (Mensualidades m : listaMensualidades) {
        boolean coincide = true;

        if (chkInquilino.isSelected()) {
            coincide = coincide && m.getNomInquilino().toLowerCase().contains(texto);
        }
        if (chkMes.isSelected()) {
            coincide = coincide && String.valueOf(m.getMesCobro()).equals(texto);
        }
        if (chkAnio.isSelected()) {
            coincide = coincide && String.valueOf(m.getAnioActual()).equals(texto);
        }
        if (!chkInquilino.isSelected() && !chkMes.isSelected() && !chkAnio.isSelected()) {
            coincide = texto.isEmpty();
        }

        if (coincide) {
            Object[] fila = {
                m.getConsecutivo(),
                m.getNumAlquiler(),
                m.getFechCreacion(),
                m.getNomInquilino(),
                m.getMesCobro(),
                m.getAnioActual(),
                m.getDescuento() + "%",
                m.getMontoMes(),
                m.getEstado()
            };
            model.addRow(fila);
        }
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbMesMostrar = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtAnioMostrar = new javax.swing.JTextField();
        btnMostrarMensualidades = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFechaActual = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbMesGenerar = new javax.swing.JComboBox<>();
        txtAnioGenerar = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMensualidades = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();
        chkInquilino = new javax.swing.JCheckBox();
        chkMes = new javax.swing.JCheckBox();
        chkAnio = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Mensualidades");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mostrar Mensualidades"));

        jLabel4.setText("Mes:");

        cmbMesMostrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero ", "Febrero ", "Marzo ", "Abril ", "Mayo ", "Junio ", "Julio ", "Agosto ", "Septiembre", "Octubre ", "Noviembre ", "Diciembre " }));

        jLabel5.setText("Año:");

        btnMostrarMensualidades.setText("Mostrar Mensualidades");
        btnMostrarMensualidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMensualidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMesMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnioMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMostrarMensualidades)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbMesMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAnioMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnMostrarMensualidades)
                .addGap(81, 81, 81))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Generar Mensualidades"));

        jLabel1.setText("Fecha Actual:");

        txtFechaActual.setEditable(false);

        jLabel2.setText("Mes:");

        jLabel3.setText("Año:");

        cmbMesGenerar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero ", "Febrero ", "Marzo ", "Abril ", "Mayo ", "Junio ", "Julio ", "Agosto ", "Septiembre", "Octubre ", "Noviembre ", "Diciembre " }));

        txtAnioGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioGenerarActionPerformed(evt);
            }
        });

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbMesGenerar, 0, 169, Short.MAX_VALUE)
                        .addComponent(txtAnioGenerar)
                        .addComponent(txtFechaActual)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbMesGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnioGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btnGenerar)
                .addGap(68, 68, 68))
        );

        jLabel6.setText("Filtrar por:");

        tblMensualidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Consecutivo", "Num Alquiler", "Fecha Creación", "Inquilino", "Mes en Cobro", "Año", "Descuento", "Monto a pagar", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblMensualidades);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        chkInquilino.setText("Inquilino");

        chkMes.setText("Mes");
        chkMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMesActionPerformed(evt);
            }
        });

        chkAnio.setText("Año");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(chkInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chkMes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFiltro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkInquilino)
                    .addComponent(chkMes)
                    .addComponent(chkAnio))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnioGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioGenerarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioGenerarActionPerformed

    /**
    * Filtra y muestra en la tabla únicamente las mensualidades del
    * mes/año seleccionado.
    */
    private void btnMostrarMensualidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMensualidadesActionPerformed
        int mes = cmbMesMostrar.getSelectedIndex() + 1;
    String textoAnio = txtAnioMostrar.getText().trim();

    if (textoAnio.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el año");
        return;
    }

    int anio;
    try {
        anio = Integer.parseInt(textoAnio);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El año debe ser un número");
        return;
    }

    String[] columnas = {"Consecutivo", "Núm Alquiler", "Fecha Creación", "Inquilino", "Mes en Cobro", "Año", "Descuento", "Monto a pagar", "Estado"};
    model = new DefaultTableModel(null, columnas);
    tblMensualidades.setModel(model);

    for (Mensualidades m : listaMensualidades) {
        if (m.getMesCobro() == mes && m.getAnioActual() == anio) {
            Object[] fila = {
                m.getConsecutivo(),
                m.getNumAlquiler(),
                m.getFechCreacion(),
                m.getNomInquilino(),
                m.getMesCobro(),
                m.getAnioActual(),
                m.getDescuento() + "%",
                m.getMontoMes(),
                m.getEstado()
            };
            model.addRow(fila);
        }
    }
    }//GEN-LAST:event_btnMostrarMensualidadesActionPerformed

    private void chkMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMesActionPerformed

    
    /**
    * Genera las mensualidades del mes/año seleccionado para todos los
    * alquileres vigentes, validando que no existan duplicados ni fechas
    * anteriores a la actual, y refresca la tabla con los resultados.
    */
    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        int mes = cmbMesGenerar.getSelectedIndex() + 1;
    String textoAnio = txtAnioGenerar.getText().trim();

    if (textoAnio.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el año");
        return;
    }

    int anio;
    try {
        anio = Integer.parseInt(textoAnio);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El año debe ser un número");
        return;
    }

    try {
        ArrayList<Mensualidades> generadas = Mensualidades.generarMensualidades(
                listaAlquileres, listaInquilinos, listaMensualidades, mes, anio);

        if (generadas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se generaron mensualidades nuevas (ya existían o no hay alquileres vigentes)");
        } else {
            JOptionPane.showMessageDialog(this, "Se generaron " + generadas.size() + " mensualidades");
        }
        mostrarDatos();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgMensualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgMensualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgMensualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgMensualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               DlgGanancias dialog = new DlgGanancias(new javax.swing.JFrame(), true, new ArrayList<Alquileres>(), new ArrayList<Mensualidades>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnMostrarMensualidades;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkAnio;
    private javax.swing.JCheckBox chkInquilino;
    private javax.swing.JCheckBox chkMes;
    private javax.swing.JComboBox<String> cmbMesGenerar;
    private javax.swing.JComboBox<String> cmbMesMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMensualidades;
    private javax.swing.JTextField txtAnioGenerar;
    private javax.swing.JTextField txtAnioMostrar;
    private javax.swing.JTextField txtFechaActual;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
