/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

/**
 * Ventana principal del módulo de Alquileres. 
 * Muestra en una tabla todos los alquileres registrados y permite crear, editar y eliminar registros llamando a DlgNewAlquiler.
 *
 * @author Erick
 */
public class DlgMainAlquileres extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgMainAlquileres.class.getName());

    /**
     * Lista de alquileres del sistema, se modifica directamente al agregar, editar o eliminar.
     */
    private java.util.ArrayList<modelo.Alquileres> listaAlquileres;

    /**
     * Lista de inquilinos registrados, se pasa a DlgNewAlquiler para su combo.
     */
    private java.util.ArrayList<modelo.Inquilino> listaInquilinos;

    /**
     * Lista de viviendas registradas, se pasa a DlgNewAlquiler} para su combo.
     */
    private java.util.ArrayList<modelo.Vivienda> listaViviendas;

    /**
     * Crea la ventana de gestión de alquileres y carga la tabla con los datos actuales.
     *
     * @param parent ventana padre desde la que se abre el diálogo
     * @param modal si el diálogo debe bloquear la ventana padre mientras está abierto
     * @param listaAlquileres lista de alquileres del sistema
     * @param listaInquilinos lista de inquilinos registrados
     * @param listaViviendas lista de viviendas registradas
     */
    public DlgMainAlquileres(java.awt.Frame parent, boolean modal,
            java.util.ArrayList<modelo.Alquileres> listaAlquileres,
            java.util.ArrayList<modelo.Inquilino> listaInquilinos,
            java.util.ArrayList<modelo.Vivienda> listaViviendas) {
        super(parent, modal);
        this.listaAlquileres = listaAlquileres;
        this.listaInquilinos = listaInquilinos;
        this.listaViviendas = listaViviendas;
        initComponents();
        cargarTabla();
    }

    /**
     * Reconstruye el modelo de la tabla a partir de la lista de alquileres actual. 
     * Se llama al abrir la ventana y después de cada Nuevo, Editar o Eliminar, para que la tabla siempre refleje los datos vigentes.
     */
    private void cargarTabla() {
        javax.swing.table.DefaultTableModel tabla = new javax.swing.table.DefaultTableModel(
                new Object[]{"Número", "Fecha", "Precio", "Estado"}, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };

        for (modelo.Alquileres a : listaAlquileres) {
            tabla.addRow(new Object[]{
                a.getNumAlquiler(),
                a.getFechaContrato(),
                a.getPrecioAlquiler(),
                a.getEstado()
            });
        }

        tblAlquileres.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlquileres = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Alquileres");

        tblAlquileres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número", "Fecha", "Precio", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblAlquileres);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addGap(12, 12, 12)
                        .addComponent(btnCerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar)
                    .addComponent(btnNuevo))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre DlgNewAlquiler en modo "nuevo" y, al cerrarse,
     * refresca la tabla para mostrar el alquiler recién agregado.
     *
     * @param evt evento de clic sobre el botón Nuevo
     */
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        DlgNewAlquiler dlg = new DlgNewAlquiler((java.awt.Frame) this.getParent(), true,
                listaAlquileres, listaInquilinos, listaViviendas);
        dlg.setVisible(true);
        cargarTabla();
    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * Toma el alquiler seleccionado en la tabla y abre {@link DlgNewAlquiler}
     * en modo "editar" con esos datos precargados. Si no hay ninguna fila
     * seleccionada, muestra un aviso y no hace nada.
     *
     * @param evt evento de clic sobre el botón Editar
     */
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tblAlquileres.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un alquiler para editar.");
            return;
        }
        modelo.Alquileres seleccionado = listaAlquileres.get(fila);
        DlgNewAlquiler dlg = new DlgNewAlquiler((java.awt.Frame) this.getParent(), true,
                listaAlquileres, listaInquilinos, listaViviendas, seleccionado);
        dlg.setVisible(true);
        cargarTabla();
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * Elimina de la lista el alquiler seleccionado en la tabla, previa
     * confirmación del usuario. Si no hay ninguna fila seleccionada,
     * muestra un aviso y no hace nada.
     *
     * @param evt evento de clic sobre el botón Eliminar
     */
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblAlquileres.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un alquiler para eliminar.");
            return;
        }
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea eliminar este alquiler?", "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            listaAlquileres.remove(fila);
            cargarTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * Cierra esta ventana y regresa al menú principal.
     *
     * @param evt evento de clic sobre el botón Cerrar
     */
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * Método de prueba para abrir esta ventana de forma independiente,
     * sin pasar por el menú principal del sistema.
     *
     * @param args argumentos de línea de comandos (no se usan)
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgMainAlquileres dialog = new DlgMainAlquileres(new javax.swing.JFrame(), true,
                        new java.util.ArrayList<>(), new java.util.ArrayList<>(), new java.util.ArrayList<>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlquileres;
    // End of variables declaration//GEN-END:variables
}
