/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.util.ArrayList;
import modelo.Propietario;
import modelo.Vivienda;
import javax.swing.JOptionPane;

/**
 * Diálogo para agregar o editar una vivienda. Permite seleccionar un propietario existente mediante un combo.
 *
 * @author Erick
 */
public class DlgNewVivienda extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgNewVivienda.class.getName());

    /**
     * Lista de viviendas donde se agrega o actualiza el registro.
     */
    private ArrayList<Vivienda> listaVivienda;

    /**
     * Lista de propietarios existentes, usada para llenar el combo.
     */
    private ArrayList<Propietario> listaProp;

    /**
     * Indica la operación a realizar: 1: Agregar, 2: Editar.
     */
    private int operacion;

    /**
     * Posición en la lista de la vivienda que se está editando.
     */
    private int index;

    /**
     * Vivienda que se está editando (solo se usa en el modo Editar).
     */
    private Vivienda vivienda;

    public DlgNewVivienda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Crea el diálogo en modo Agregar.
     *
     * @param parent ventana padre
     * @param modal si el diálogo es modal
     * @param listaVivienda lista donde se agregará la nueva vivienda
     * @param listaProp lista de propietarios existentes para el combo
     * @param operacion 1 para agregar
     */
    public DlgNewVivienda(java.awt.Frame parent, boolean modal, ArrayList<Vivienda> listaVivienda, ArrayList<Propietario> listaProp, int operacion) {
        super(parent, modal);
        initComponents();
        this.listaVivienda = listaVivienda;
        this.listaProp = listaProp;
        this.operacion = operacion;
        poblarCmbPropietario();
    }

    /**
     * Crea el diálogo en modo Editar, con los campos ya llenos.
     *
     * @param parent ventana padre
     * @param modal si el diálogo es modal
     * @param listaVivienda lista donde se actualizará la vivienda
     * @param listaProp lista de propietarios existentes para el combo
     * @param operacion 2 para editar
     * @param vivienda vivienda a editar
     * @param index posición de la vivienda en la lista
     */
    public DlgNewVivienda(java.awt.Frame parent, boolean modal, ArrayList<Vivienda> listaVivienda, ArrayList<Propietario> listaProp, int operacion, Vivienda vivienda, int index) {
        super(parent, modal);
        initComponents();
        this.listaVivienda = listaVivienda;
        this.listaProp = listaProp;
        this.operacion = operacion;
        this.vivienda = vivienda;
        this.index = index;
        poblarCmbPropietario();
        llenarCampos();
    }

    /**
     * Obtiene la lista de viviendas, ya actualizada tras guardar.
     *
     * @return la listaVivienda
     */
    public ArrayList<Vivienda> getListaVivienda() {
        return listaVivienda;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescripcion = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtMtsConstruc = new javax.swing.JTextField();
        cmbMaterial = new javax.swing.JComboBox<>();
        txtCantHabitac = new javax.swing.JTextField();
        cmbCarretera = new javax.swing.JComboBox<>();
        txtDepositoGarantia = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtMtsLote = new javax.swing.JTextField();
        chkCochera = new javax.swing.JCheckBox();
        txtCantBanios = new javax.swing.JTextField();
        txtPrecioBase = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblMtsConstrucc = new javax.swing.JLabel();
        lblMaterial = new javax.swing.JLabel();
        lblCantHabitac = new javax.swing.JLabel();
        lblCarretera = new javax.swing.JLabel();
        cmbPropietario = new javax.swing.JComboBox<>();
        lblDepositoGarantia = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblMtsLote = new javax.swing.JLabel();
        lblCochera = new javax.swing.JLabel();
        lblCantBaños = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtDireccion.addActionListener(this::txtDireccionActionPerformed);

        cmbMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Block", "Baldosa", "Super block", "Madera", "Mixta" }));

        txtCantHabitac.addActionListener(this::txtCantHabitacActionPerformed);

        cmbCarretera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lastre", "Pavimento" }));

        txtDepositoGarantia.addActionListener(this::txtDepositoGarantiaActionPerformed);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Alquilada", "Inactiva" }));
        cmbEstado.addActionListener(this::cmbEstadoActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnCancelar.setText("Cancelar");

        chkCochera.setText("Cochera");

        lblDescripcion.setText("Descripción:");

        lblDireccion.setText("Dirección:");

        lblMtsConstrucc.setText("Mts Construcc");

        lblMaterial.setText("Material:");

        lblCantHabitac.setText("Cant Habitac:");

        lblCarretera.setText("Carretera");

        cmbPropietario.addActionListener(this::cmbPropietarioActionPerformed);

        lblDepositoGarantia.setText("Depósito Garantia:");

        lblEstado.setText("Estado:");

        lblMtsLote.setText("Mts Lote:");

        lblCochera.setText("Cochera:");

        lblCantBaños.setText("Cant Baños:");

        jLabel1.setText("Precio Base:");

        jLabel2.setText("Propietario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDepositoGarantia)
                            .addComponent(lblMtsConstrucc)
                            .addComponent(lblMaterial)
                            .addComponent(lblCarretera))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCantHabitac, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDepositoGarantia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCarretera, javax.swing.GroupLayout.Alignment.LEADING, 0, 112, Short.MAX_VALUE)
                            .addComponent(txtCantHabitac, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantBaños)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMtsLote)
                            .addComponent(txtCantBanios)
                            .addComponent(chkCochera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrecioBase)
                            .addComponent(cmbPropietario, 0, 112, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbMaterial, 0, 112, Short.MAX_VALUE)
                                .addComponent(txtMtsConstruc))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCochera, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblMtsLote, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(160, 160, 160))
                        .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)))
                .addGap(30, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccion))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMtsConstruc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMtsLote, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMtsConstrucc)
                    .addComponent(lblMtsLote))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkCochera, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaterial)
                    .addComponent(lblCochera))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblCantHabitac, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCantBanios, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(lblCantBaños))
                    .addComponent(txtCantHabitac, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbCarretera, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCarretera)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDepositoGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepositoGarantia)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Llena el combo de propietarios con los propietarios existentes.
     */
    private void poblarCmbPropietario() {
        cmbPropietario.removeAllItems();
        for (Propietario p : listaProp) {
            cmbPropietario.addItem(p);
        }
    }

    /**
     * Rellena los campos del formulario con los datos de la vivienda a editar.
     */
    private void llenarCampos() {
        txtDescripcion.setText(vivienda.getDescripcion());
        txtDireccion.setText(vivienda.getDireccion());
        txtMtsConstruc.setText(String.valueOf(vivienda.getMtsConstruc()));
        txtMtsLote.setText(String.valueOf(vivienda.getMtsLote()));
        cmbMaterial.setSelectedItem(vivienda.getMaterialConstruc());
        chkCochera.setSelected(vivienda.isCochera());
        txtCantHabitac.setText(String.valueOf(vivienda.getCantHabitac()));
        txtCantBanios.setText(String.valueOf(vivienda.getCantBanios()));
        cmbCarretera.setSelectedItem(vivienda.getCarretera());
        txtPrecioBase.setText(String.valueOf(vivienda.getPrecioBase()));
        txtDepositoGarantia.setText(String.valueOf(vivienda.getDepositoGarantia()));
        cmbPropietario.setSelectedItem(vivienda.getPropietario());
        cmbEstado.setSelectedItem(vivienda.getEstado());
    }

    /**
     * Valida los campos del formulario y construye la vivienda a guardar. Muestra un mensaje si hay campos vacíos o datos numéricos inválidos.
     *
     * @return la vivienda construida, o null si la validación falla
     */
    private Vivienda getVivienda() {
        Vivienda nuevaVivienda = new Vivienda();

        if (!txtDescripcion.getText().isEmpty()
                && !txtDireccion.getText().isEmpty()
                && !txtMtsConstruc.getText().isEmpty()
                && !txtMtsLote.getText().isEmpty()
                && !txtCantHabitac.getText().isEmpty()
                && !txtCantBanios.getText().isEmpty()
                && !txtPrecioBase.getText().isEmpty()
                && !txtDepositoGarantia.getText().isEmpty()
                && cmbPropietario.getSelectedItem() != null
                && cmbEstado.getSelectedIndex() != -1) {
            try {
                nuevaVivienda.setDescripcion(txtDescripcion.getText());
                nuevaVivienda.setDireccion(txtDireccion.getText());
                nuevaVivienda.setMtsConstruc(Double.parseDouble(txtMtsConstruc.getText()));
                nuevaVivienda.setMtsLote(Double.parseDouble(txtMtsLote.getText()));
                nuevaVivienda.setMaterialConstruc(cmbMaterial.getSelectedItem().toString());
                nuevaVivienda.setCochera(chkCochera.isSelected());
                nuevaVivienda.setCantHabitac(Integer.parseInt(txtCantHabitac.getText()));
                nuevaVivienda.setCantBanios(Double.parseDouble(txtCantBanios.getText()));
                nuevaVivienda.setCarretera(cmbCarretera.getSelectedItem().toString());
                nuevaVivienda.setPrecioBase(Double.parseDouble(txtPrecioBase.getText()));
                nuevaVivienda.setDepositoGarantia(Double.parseDouble(txtDepositoGarantia.getText()));
                nuevaVivienda.setPropietario((Propietario) cmbPropietario.getSelectedItem());
                nuevaVivienda.setEstado(cmbEstado.getSelectedItem().toString());

                if (operacion == 2) {
                    nuevaVivienda.setIdVivienda(vivienda.getIdVivienda());
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Verifique que metros, habitaciones, baños, precio y depósito sean numéricos");
                return null;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hay campos vacíos");
            return null;
        }
        return nuevaVivienda;
    }

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCantHabitacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantHabitacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantHabitacActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void txtDepositoGarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepositoGarantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepositoGarantiaActionPerformed

    private void cmbPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPropietarioActionPerformed

    /**
    * Guarda la vivienda del formulario. Si la operación es agregar, la añade
    * a la lista, si es editar, reemplaza la vivienda en su posición original.
    *
    * @param evt evento de clic sobre el botón Guardar
    */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Vivienda nuevaVivienda = getVivienda();
        if (nuevaVivienda != null) {
            if (operacion == 1) {
                listaVivienda.add(nuevaVivienda);
                JOptionPane.showMessageDialog(this, "Vivienda guardada");
            } else {
                listaVivienda.set(index, nuevaVivienda);
                JOptionPane.showMessageDialog(this, "Vivienda editada");
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgNewVivienda dialog = new DlgNewVivienda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chkCochera;
    private javax.swing.JComboBox<String> cmbCarretera;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbMaterial;
    private javax.swing.JComboBox<Propietario> cmbPropietario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCantBaños;
    private javax.swing.JLabel lblCantHabitac;
    private javax.swing.JLabel lblCarretera;
    private javax.swing.JLabel lblCochera;
    private javax.swing.JLabel lblDepositoGarantia;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblMaterial;
    private javax.swing.JLabel lblMtsConstrucc;
    private javax.swing.JLabel lblMtsLote;
    private javax.swing.JTextField txtCantBanios;
    private javax.swing.JTextField txtCantHabitac;
    private javax.swing.JTextField txtDepositoGarantia;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMtsConstruc;
    private javax.swing.JTextField txtMtsLote;
    private javax.swing.JTextField txtPrecioBase;
    // End of variables declaration//GEN-END:variables
}
